# Generated by Django 5.0.2 on 2024-03-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0003_movies_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="director",
            field=models.CharField(max_length=200),
        ),
    ]
