# Generated by Django 5.0.2 on 2024-03-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0005_movies_added_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="review",
            field=models.TextField(blank=True),
        ),
    ]
